### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by molysgaard** [betaflight/betaflight-esc#32]
Hi, I am interested in contributing to this project. Got extensive experience with embedded electronics.

I know this is very early days of the project, so if it is not the right time I understand.
I really see the appeal of an open source ESC implementation that also is readable C-code, and thus I am a bit eager to start fiddling around on this project and perhaps contribute some hours.

Would it be possible to create some minimal instructions for getting the software up and running in the README.md?

Eg.
1) Needed hardware to run on: preferably an explanation of which ESCs you are currently targeting.
2) Needed hardware to flash/program/debug the hardware, eg. Segger JLink, Black Magic Probe etc.
3) Needed build environment, eg Linux, gnu-arm-none-eabi, needed packages/libraries etc...
4) How to program hardware, flashing instructions.
5) How to run test that everything is working, blink a led, beep the motor, spin the motor.

**Comment by brycedjohnson** [comment]
Yeah a build guide needs to get make up, but here is the quick summary.

1. Only have the fishdrone esc right now, but others should be able to be supported, just need target files made.  Blheli32, Kiss that use the stm32f0 processors should be supported (assuming they aren't debug locked).  An older vgood arm esc had the chip locked and debug disabled, so that won't work unless you swap the uC.

2. I'm using an cheap clone st-link2 and I got GDB debugging.  Jlink should probaby work as well.

3. Pull down the code with git. I'm in windows so I use cygwin to build.  Need to install curl and a couple other things I can't remember off the top of my head... Buildling it in the same way as betaflight if you have done that before.

This would probably work as well: https://github.com/betaflight/betaflight/wiki/Building-Betaflight-on-Windows,-the-Linux-subsystem-way

Then:

`make arm_sdk_install` grabs the toolchain - 
`make fishdrone` to build the fishdrone esc

4.  Solder up to the SWD/SWIO/GND pins.  Use GDB or st-link utility to load the code. 

5. There is a CLI to change LED color and check ADCs.  Not yet spinning a motor.

Join the #open_esc_firmware channel on slack.  betaflight.ch with an email should auto send you an invite.

**Comment by molysgaard** [comment]
Thanks for the thorough answer @brycedjohnson.
I have one small question, where can I find this fishdrone ESC?
I know of the fishpepper ESC, but it is 8-bit, so it's not that one?

**Comment by mikeller** [comment]
@molysgaard: @Linjieqiang might be able to help with that.

**Comment by Linjieqiang** [comment]
Hello @molysgaard ,thanks for your watch.If you need some samples,please contact me with Betaflight Slack.
